import CommonImg from "../../assets/singleProductImg/xiaomiCommonImg.jpg";

export const relatedProductsData = [
  {
    id: 1,
    img: CommonImg,
    name: "Xiaomi Redmi Note 10 Only sell (Used)",
    location: "Chattogram, Mobile Phones",
    price: "Tk 15,800",
    releaseTime: "just now",
  },
  {
    id: 2,
    img: "https://i.ibb.co/Ch2FsC9/download.jpg",
    name: "Apple iPhone 14pro Max . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 148,000",
    releaseTime: "just now",
  },
  {
    id: 3,
    img: "https://i.ibb.co/z49g0F9/images-3.jpg",
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 22,000",
    releaseTime: "1 minutes",
  },
  {
    id: 4,
    img: "https://i.ibb.co/8xTsgP5/Apple-i-Phone13-Inside4.jpg",
    name: "Apple iPhone 7S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 37,000",
    releaseTime: "2 minutes",
  },
  {
    id: 5,
    img: "https://i.ibb.co/gPQsyfP/images.jpg",
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 77,000",
    releaseTime: "9 minutes",
  },
  {
    id: 6,
    img: "https://i.ibb.co/gPQsyfP/images.jpg",
    name: "Apple iPhone 8S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 82,000",
    releaseTime: "7 minutes",
  },
  {
    id: 7,
    img: "https://i.ibb.co/XbsNshq/images-1.jpg",
    name: "Apple iPhone 11 Pro Max . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 55,000",
    releaseTime: "17 minutes",
  },
  {
    id: 8,
    img: "https://i.ibb.co/CzDrfk5/images-2.jpg",
    name: "Xiaomi Redmi Note 9 Pro Max . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 32,000",
    releaseTime: "51 minutes",
  },
  {
    id: 9,
    img: "https://i.ibb.co/nbQqFb3/20220404-Samsung-A13.jpg",
    name: "Apple iPhone 9Pro Max . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 26,000",
    releaseTime: "31 minutes",
  },
  {
    id: 10,
    img: "https://i.ibb.co/Jky7rF2/Reno6-Pro-Diwali-Edition.jpg",
    name: "Samsung Galaxy W99 . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 16,000",
    releaseTime: "7 minutes",
  },
  {
    id: 11,
    img: "https://i.ibb.co/x8WfKb2/samsung-galaxy-s22-ultra-and-regular-in-hand-htg.webp",
    name: "Oppo Z88 . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 72,000",
    releaseTime: "26 minutes",
  },
  {
    id: 12,
    img: "https://i.ibb.co/WvPqgHJ/xiaomi-mi-10-review-1024x753.jpg",
    name: "Xiaomi 12 pro max . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 88,000",
    releaseTime: "1 minutes",
  },
];