import CommonImg from "../../assets/singleProductImg/xiaomiCommonImg.jpg";

export const productsData = [
  {
    id: 1,
    img: CommonImg,
    name: "Xiaomi Redmi Note 10 Only sell (Used)",
    location: "Chattogram, Mobile Phones",
    price: "Tk 15,800",
    releaseTime: "just now",
  },
  {
    id: 2,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "just now",
  },
  {
    id: 3,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "1 minutes",
  },
  {
    id: 4,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "2 minutes",
  },
  {
    id: 5,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "9 minutes",
  },
  {
    id: 6,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "7 minutes",
  },
  {
    id: 7,
    img: CommonImg,
    name: "Apple iPhone 11 Pro Max . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "17 minutes",
  },
  {
    id: 8,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "14 minutes",
  },
  {
    id: 9,
    img: CommonImg,
    name: "Apple iPhone 6S . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "31 minutes",
  },
  {
    id: 10,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "55 minutes",
  },
  {
    id: 11,
    img: CommonImg,
    name: "Apple iPhone 6S . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "26 minutes",
  },
  {
    id: 12,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "2 minutes",
  },
  {
    id: 13,
    img: CommonImg,
    name: "Apple iPhone 6S . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "21 minutes",
  },
  {
    id: 14,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "22 minutes",
  },
  {
    id: 15,
    img: CommonImg,
    name: "Apple iPhone 6S . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "40 minutes",
  },
  {
    id: 16,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "30 minutes",
  },
  {
    id: 17,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "20 minutes",
  },
  {
    id: 18,
    img: CommonImg,
    name: "Apple iPhone 6S . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "7 minutes",
  },
  {
    id: 19,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "21 minutes",
  },
  {
    id: 20,
    img: CommonImg,
    name: "Apple iPhone 6S . (Used)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "24 minutes",
  },
  {
    id: 21,
    img: CommonImg,
    name: "Vivo Y21 . (New)",
    location: "Dhaka, Mobile Phones",
    price: "Tk 52,000",
    releaseTime: "58 minutes",
  },
];